# Generated by Django 4.2.23 on 2026-04-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('A', 'Блок A'), ('B', 'Блок B'), ('C', 'Блок C')], max_length=1, verbose_name='Блок')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('number', models.CharField(max_length=10, verbose_name='№ Квартиры')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площадь м2')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая цена ($)')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО покупателя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты ($)')),
                ('date', models.DateField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='api.client'),
        ),
    ]
