# Generated by Django 4.2.23 on 2026-04-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='last_payment_note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка к последнему платежу'),
        ),
    ]
