# Generated by Django 4.2.23 on 2026-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apartment_last_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
