# Generated by Django 4.2.23 on 2026-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apartment_currency_client_passport_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена по договору'),
        ),
    ]
